export let products = [
  {
    id: "1",
    name: "shirt",
    price: 100,
    image: "/images/shirt.jpg",
    category: "shirts",
    description: "A comfortable cotton shirt. Perfect for casual wear.",
  },
  {
    id: "2",
    name: "jeans",
    price: 200,
    image: "/images/jeans.jpg",
    category: "pants",
    description: "Stylish denim jeans with a modern fit.",
  },
  {
    id: "3",
    name: "Polo Shirt",
    price: 120,
    image: "/images/polo-shirt.jpg",
    category: "shirts",
    description: "Classic polo shirt with a modern collar design.",
  },
  {
    id: "4",
    name: "Leather Jacket",
    price: 350,
    image: "/images/leather-jacket.jpg",
    category: "jackets",
    description: "Premium leather jacket with zip closure and pockets.",
  },
  {
    id: "5",
    name: "Sneakers",
    price: 150,
    image: "/images/sneakers.jpg",
    category: "shoes",
    description: "Comfortable running sneakers with cushioned sole.",
  },
  {
    id: "6",
    name: "Casual Dress",
    price: 180,
    image: "/images/casual-dress.jpg",
    category: "dresses",
    description: "Elegant casual dress perfect for any occasion.",
  },
  {
    id: "7",
    name: "Chino Pants",
    price: 140,
    image: "/images/chino-pants.jpg",
    category: "pants",
    description: "Slim-fit chino pants in khaki color.",
  },
  {
    id: "8",
    name: "Hoodie",
    price: 90,
    image: "/images/hoodie.jpg",
    category: "hoodies",
    description: "Cozy fleece hoodie with front pocket.",
  },
  {
    id: "9",
    name: "Summer Dress",
    price: 220,
    image: "/images/summer-dress.jpg",
    category: "dresses",
    description: "Lightweight floral summer dress.",
  },
  {
    id: "10",
    name: "Running Shoes",
    price: 180,
    image: "/images/running-shoes.jpg",
    category: "shoes",
    description: "High-performance running shoes with breathable mesh.",
  },
  {
    id: "11",
    name: "Denim Jacket",
    price: 190,
    image: "/images/denim-jacket.jpg",
    category: "jackets",
    description: "Classic blue denim jacket with button closure.",
  },
  {
    id: "12",
    name: "V-Neck T-Shirt",
    price: 60,
    image: "/images/vneck-tshirt.jpg",
    category: "shirts",
    description: "Soft cotton v-neck t-shirt available in multiple colors.",
  },
  {
    id: "13",
    name: "Shorts",
    price: 80,
    image: "/images/shorts.jpg",
    category: "pants",
    description: "Comfortable summer shorts with elastic waist.",
  },
  {
    id: "14",
    name: "Winter Coat",
    price: 450,
    image: "/images/winter-coat.jpg",
    category: "jackets",
    description: "Warm insulated winter coat with hood.",
  },
  {
    id: "15",
    name: "Formal Shirt",
    price: 130,
    image: "/images/formal-shirt.jpg",
    category: "shirts",
    description: "Crisp white formal shirt perfect for business wear.",
  },
];
